### PR TITLE
Check if Rails.env is defined

### LINKED ISSUE #1503: Rails 4.2 issue: undefined method `env' for Rails:Module
Hello,

I'm working on a Rails migration (from Rails 4.1 to Rails 4.2) and I found this error: 

```
NoMethodError:
  undefined method `env' for Rails:Module
# /Users/etagwerker/Projects/ombulabs/ombushop/vendor/bundle/ruby/2.3.0/gems/simple_form-3.5.0/lib/simple_form.rb:167:in `<module:SimpleForm>'
# /Users/etagwerker/Projects/ombulabs/ombushop/vendor/bundle/ruby/2.3.0/gems/simple_form-3.5.0/lib/simple_form.rb:8:in `<top (required)>'
# /Users/etagwerker/Projects/ombulabs/ombushop/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
# /Users/etagwerker/Projects/ombulabs/ombushop/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/etagwerker/Projects/ombulabs/ombushop/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/etagwerker/Projects/ombulabs/ombushop/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
# /Users/etagwerker/Projects/ombulabs/ombushop/components/directory/lib/directory.rb:5:in `<top (required)>'
# ./lib/router_client.rb:5:in `require'
# ./lib/router_client.rb:5:in `<top (required)>'
# ./spec/spec_helper.rb:2:in `require'
# ./spec/spec_helper.rb:2:in `<top (required)>'
# ./spec/router_client_spec.rb:1:in `require'
# ./spec/router_client_spec.rb:1:in `<top (required)>'
No examples found.
```

It's a component based Rails engine which uses this architecture: http://shageman.github.io/cbra.info/

The problem is that I'm not doing a `require "rails"` before I `require "simple_form"`. I don't want to do that, because this particular component doesn't really need to require "rails". 

I think the best solution would be to change the code in `simple_form` to check for `if defined?(Rails.env)` (I saw a similar solution here: https://github.com/haml/haml/commit/ad2503cf9b3a5680f20b6845d51692e8d200db01) 

The code here: https://github.com/plataformatec/simple_form/blob/master/lib/simple_form.rb#L166 would then look like this: 

```
@@cache_discovery = defined?(Rails.env) && !Rails.env.development?
```

My component works fine in Rails 4.1, but it fails in Rails 4.2

If you're interested I can submit a pull request.

Please let me know.

Thanks!

### PR DESCRIPTION
**Pull request by etagwerker**
Hello, 

This PR fixes #1503 by making the condition more specific. 

Please check it out and let me know if you have any comments.

Thanks!

### CODE REVIEW

**Comment by benlangfeld** [comment]
@rafaelfranca Do you have an estimate for when this might be released? It would be very helpful for me across a large number of engines.
